rules:
  # Allow formBodyErrors.BASE_TYPE_CHOICES, for example
  new-cap:
  - 1
  - properties: false

  # https://github.com/microsoft/TypeScript/issues/15300
  '@typescript-eslint/ban-types':
  - 2
  - extendDefaults: true
    types:
      object: false
  '@typescript-eslint/prefer-readonly-parameter-types': 0

overrides:
- files: index.ts
  rules:
    import/no-unused-modules: 0
