name: CI
on:
- push
- pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install
      run: npm i -g pnpm && pnpm i
    - name: Lint
      run: pnpm run lint && pnpm run lint:md
    - name: Typecheck
      run: pnpm run typecheck
    - name: Build
      run: pnpm run build
    - name: Test
      run: pnpm run test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install
      run: npm i -g pnpm && pnpm i
    - name: Release
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
